name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Go Packages
        run: go mod tidy
        working-directory: ./fastzip4jlib

      - name: Build Go Lib
        run: |
          ./build.sh
          # Ensure the libraries have proper permissions
          chmod 755 ../fastzip4j/src/main/resources/lib/*.so
          chmod 755 ../fastzip4j/src/main/resources/lib/*.dylib
          chmod 755 ../fastzip4j/src/main/resources/lib/*.dll
        working-directory: ./fastzip4jlib
      
      - name: Verify Go Libraries
        run: |
          echo "Checking Go libraries in resources directory:"
          ls -la ./src/main/resources/lib/
          echo "File types:"
          file ./src/main/resources/lib/libfastzip4j.*
          echo "File permissions:"
          stat ./src/main/resources/lib/libfastzip4j.*
        working-directory: ./fastzip4j

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven
        run: sudo apt-get install -y maven
        working-directory: ./fastzip4j

      - name: Build artifact
        run: mvn clean install -Dgpg.skip=true
        working-directory: ./fastzip4j
        
      - name: Check Go compile library
        working-directory: ./fastzip4j
        run: |
          ls ./src/main/resources/lib