name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Cross-Compilation Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 gcc-mingw-w64
          sudo apt-get install -y gcc-multilib g++-multilib
          sudo apt-get install -y musl-tools

      - name: Install Go Packages
        run: go mod tidy
        working-directory: ./fastzip4jlib

      - name: Build Go Lib
        run: |
          chmod +x ./build.sh
          ./build.sh
        working-directory: ./fastzip4jlib
      
      - name: Verify Go Libraries
        run: |
          echo "Checking Go libraries in resources directory:"
          ls -la ./src/main/resources/lib/
          echo "File types:"
          file ./src/main/resources/lib/libfastzip4j.*
          echo "File permissions:"
          stat ./src/main/resources/lib/libfastzip4j.*
          echo "Verifying library formats:"
          objdump -f ./src/main/resources/lib/libfastzip4j.so | grep -i "file format"
          x86_64-w64-mingw32-objdump -f ./src/main/resources/lib/libfastzip4j.dll | grep -i "file format"
        working-directory: ./fastzip4j

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven
        run: sudo apt-get install -y maven
        working-directory: ./fastzip4j

      - name: Build artifact
        run: mvn clean install -Dgpg.skip=true -Drevision=SNAPSHOT
        working-directory: ./fastzip4j
        
      - name: Verify JAR Contents
        run: |
          echo "Checking contents of the built JAR:"
          jar tf target/fastzip4j-SNAPSHOT.jar | grep libfastzip4j
        working-directory: ./fastzip4j

      - name: Check Go compile library
        working-directory: ./fastzip4j
        run: |
          ls ./src/main/resources/lib
