name: Build Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Go Packages
        run: go mod tidy
        working-directory: ./fastzip4jlib

      - name: Build Go Lib for Windows
        run: |
          mkdir -p ..\fastzip4j\src\main\resources\lib\
          $env:GOOS="windows"; $env:GOARCH="amd64"; $env:CGO_ENABLED="1"; go build -buildmode=c-shared -o ..\fastzip4j\src\main\resources\lib\libfastzip4j.dll fastzip4j.go
        shell: pwsh
        working-directory: ./fastzip4jlib

      - name: Verify Go Libraries
        run: |
          echo "Checking Go libraries in resources directory:"
          dir ..\fastzip4j\src\main\resources\lib\
        shell: cmd
        working-directory: ./fastzip4jlib

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven
        uses: actions/setup-maven@v4
        with:
          maven-version: '3.9.6' # Or install manually if needed

      - name: Build artifact
        run: mvn clean install -Dgpg.skip=true -Drevision=SNAPSHOT
        working-directory: ./fastzip4j

      - name: Verify JAR Contents
        run: |
          echo "Checking contents of the built JAR:"
          jar tf target\fastzip4j-SNAPSHOT.jar | findstr libfastzip4j
        shell: cmd
        working-directory: ./fastzip4j

      - name: Check Go compile library
        run: |
          dir src\main\resources\lib
        shell: cmd
        working-directory: ./fastzip4j