name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Go Packages
        run: go mod tidy
        working-directory: ./fastzip4jlib

      - name: Build Go Lib
        run: ./build.sh
        working-directory: ./fastzip4jlib

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven
        run: sudo apt-get install -y maven
        working-directory: ./fastzip4j

      - name: Extract Version from Tag
        id: extract_version
        if: startsWith(github.ref, 'refs/tags/') # Only run this step for tags
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build artifact
        run: mvn clean install -Dproject.version=${{ env.VERSION || 'SNAPSHOT' }}
        working-directory: ./fastzip4j
      
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/') # Only deploy on tag creation
        run: mvn deploy -Dproject.version=${{ env.VERSION }}
        working-directory: ./fastzip4j
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}