name: Deploy to GitHub Packages

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Go Packages
        run: go mod tidy
        working-directory: ./fastzip4jlib

      - name: Build Go Lib
        run: ./build.sh
        working-directory: ./fastzip4jlib

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: ossrh
          server-username: ${{ secrets.MAVEN_CENTRAL_REPO_USERNAME }}
          server-password: ${{ secrets.MAVEN_CENTRAL_REPO_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Maven
        run: sudo apt-get install -y maven

      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          # Remove 'v' prefix if it exists
          VERSION=${VERSION#v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: ${VERSION}"

      - name: Configure Maven for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>\${env.GITHUB_ACTOR}</username>
                <password>\${env.GITHUB_TOKEN}</password>
              </server>
              <server>
                <id>ossrh</id>
                <username>\${env.MAVEN_USERNAME}</username>
                <password>\${env.MAVEN_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build artifact
        run: mvn clean install -Dproject.version=${{ env.VERSION }} -Dgpg.skip=true
        working-directory: ./fastzip4j

      - name: Publish to Apache Maven Central
        run: mvn --batch-mode deploy -Dproject.version=${{ env.VERSION }}
        working-directory: ./fastzip4j
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_REPO_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Deploy to GitHub Packages
        run: mvn deploy -Dproject.version=${{ env.VERSION }} -Dgpg.skip=true
        working-directory: ./fastzip4j
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}