name: Deploy to GitHub Packages

on:
  push:
    tags:
      - '*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Install Go Packages
        run: go mod tidy
        working-directory: ./fastzip4jlib

      - name: Build Go Lib
        run: |
          ./build.sh
          # Ensure the libraries have proper permissions
          chmod 755 ../fastzip4j/src/main/resources/lib/*.so
          chmod 755 ../fastzip4j/src/main/resources/lib/*.dylib
          chmod 755 ../fastzip4j/src/main/resources/lib/*.dll
        working-directory: ./fastzip4jlib

      - name: Verify Go Libraries
        run: |
          echo "Checking Go libraries in resources directory:"
          ls -la ./src/main/resources/lib/
          echo "File types:"
          file ./src/main/resources/lib/libfastzip4j.*
          echo "File permissions:"
          stat ./src/main/resources/lib/libfastzip4j.*
        working-directory: ./fastzip4j

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: ossrh
          server-username: ${{ secrets.MAVEN_CENTRAL_REPO_USERNAME }}
          server-password: ${{ secrets.MAVEN_CENTRAL_REPO_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Maven
        run: sudo apt-get install -y maven

      - name: Extract Version from Tag
        id: extract_version
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION=${{ github.event.release.tag_name }}
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          # Remove 'v' prefix if it exists
          VERSION=${VERSION#v}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: ${VERSION}"

      - name: Build artifact
        run: mvn clean install -Dproject.version=${{ env.VERSION }}
        working-directory: ./fastzip4j
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Verify JAR Contents
        run: |
          echo "Checking contents of the built JAR:"
          jar tf target/fastzip4j-${VERSION}.jar | grep libfastzip4j
        working-directory: ./fastzip4j

      - name: Check Go compile library
        working-directory: ./fastzip4j
        run: |
          ls ./src/main/resources/lib

      - name: Configure Maven for GitHub Packages
        if: github.event_name == 'release'
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>\${env.GITHUB_ACTOR}</username>
                <password>\${env.GITHUB_TOKEN}</password>
              </server>
              <server>
                <id>central</id>
                <username>\${env.MAVEN_USERNAME}</username>
                <password>\${env.MAVEN_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to GitHub Packages
        if: github.event_name == 'release'
        run: mvn deploy -Dproject.version=${{ env.VERSION }} -Dgpg.skip=true
        working-directory: ./fastzip4j
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Maven Central
        if: github.event_name == 'release'
        run: mvn --batch-mode deploy -Dproject.version=${{ env.VERSION }}
        working-directory: ./fastzip4j
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_REPO_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      